customhost = "internship.cxtk9ixv8wey.us-east-1.rds.amazonaws.com"
customuser = "awsuser"
custompwd = "Bait3273"
customdb = "internship"
custombucket = "diongziyu-bucket"
customregion = "us-east-1"